### ISSUE TITLE
Dependency io.micrometer.prometheus.PrometheusMeterRegistry is deprecated and breaks build

### ISSUE THREAD

**Issue by michaelkoepf** [dynatrace-research/ShuffleBench#1]
**Describe the bug**

As of Micrometer Registry Prometheus 1.13, `io.micrometer.prometheus.PrometheusMeterRegistry` is [deprecated](https://github.com/spring-projects/spring-boot/issues/39904) which breaks the build of the `latency-exporter` module.

An immediate fix that can be applied without extensive testing is to set the version of the dependcy `'io.micrometer:micrometer-registry-prometheus'` to the previous minor version 1.12.9 instead of `latest.release`.

**To Reproduce**

`./gradlew build`

Build fails on module `latency-exporter` with an error.

**Expected behavior**

Build should be successful.

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04
- Java: openjdk 11.0.23

**Comment by SoerenHenning** [comment]
Thank for reporting this issue. It is now fixed with 7bea8039ccbf0003000b2ecf7bd995a797f49d3c.
